# Generated by Django 3.0.8 on 2020-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('total', models.FloatField(max_length=12)),
                ('quantity', models.FloatField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
