# Generated by Django 3.0.8 on 2020-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200710_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
