# Generated by Django 3.0.8 on 2020-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200712_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='id',
            field=models.IntegerField(primary_key=models.CharField(max_length=100), serialize=False),
        ),
    ]
